### ISSUE TITLE
Support for Cathay Bank [TW]

### ISSUE THREAD

**Issue by nocalla** [torbengb/bank2ynab#140]
Name of Bank: Cathay
Country: TW Taiwan

Source: [johnlinvc/ynab_tw](https://github.com/johnlinvc/ynab_tw)

**To be filled in as required. Delete fields that match default values.**
Source Filename Pattern = example_transaction_export_filename
Source Filename Extension = .csv
Use Regex for Filename = False
Source CSV Delimiter = ,
Source Has Column Headers = True
Input Columns = Date,Payee,Outflow,Inflow,Running Balance
Plugin =

Master issue #21

**Comment by torbengb** [comment]
I trawled through the original code and found these cool samples:

credit:

    您本月各幣別消費明細如下：
    新臺幣：
    消費日,入帳起息日,交易說明,新臺幣金額,卡號後四碼,行動卡號後四碼,消費國家,幣別,外幣金額,折算日
    10/03, 10/03, ＦＩＳＣ跨行轉帳繳款, -1792, 1234, , , TWD, , --
    , , 繳款金額小計:, -1792, , , , , , 
    09/28, 10/03, ＭＩＯＰＡＮＥ, 456, 1234, , TW, TWD, 0.00, --
    , , 新增交易金額小計:, 456, , , , , , 

withdraw:

    帳號:00000000000000,起始日:20160927,終止日:20161003
    日期,提出,存入,餘額,說明,備註,特別備註
    20161003, 5000, , 12345, 自行提款, 00000000, 

This [translates](https://translate.google.com/#auto/en/%E6%82%A8%E6%9C%AC%E6%9C%88%E5%90%84%E5%B9%A3%E5%88%A5%E6%B6%88%E8%B2%BB%E6%98%8E%E7%B4%B0%E5%A6%82%E4%B8%8B%EF%BC%9A%0A%E6%96%B0%E8%87%BA%E5%B9%A3%EF%BC%9A%0A%E6%B6%88%E8%B2%BB%E6%97%A5%2C%E5%85%A5%E5%B8%B3%E8%B5%B7%E6%81%AF%E6%97%A5%2C%E4%BA%A4%E6%98%93%E8%AA%AA%E6%98%8E%2C%E6%96%B0%E8%87%BA%E5%B9%A3%E9%87%91%E9%A1%8D%2C%E5%8D%A1%E8%99%9F%E5%BE%8C%E5%9B%9B%E7%A2%BC%2C%E8%A1%8C%E5%8B%95%E5%8D%A1%E8%99%9F%E5%BE%8C%E5%9B%9B%E7%A2%BC%2C%E6%B6%88%E8%B2%BB%E5%9C%8B%E5%AE%B6%2C%E5%B9%A3%E5%88%A5%2C%E5%A4%96%E5%B9%A3%E9%87%91%E9%A1%8D%2C%E6%8A%98%E7%AE%97%E6%97%A5) as follows:

credit:  

    Your monthly spending details are as follows:
    NT:
    Consumer Day, Book Value Date, Transaction Description, NT Amount, Card Number Four, Code Number Four, Consumer Countries, Currency, Foreign Currency, Conversion Date
    10/03, 10/03, FISC Interbank Payments, -1792, 1234,,, TWD, -
    Subtotal:, -1792,,,,,,
    09/28, 10/03, MIOPANE, 456, 1234, TW, TWD, 0.00, -
    ,, The new transaction amount Subtotal :, 456,,,,,,

withdraw:  

    Account number: 00000000000000, starting date: 20160927, ending date: 20161003
    Date, proposed, deposited, balance, description, notes, special notes
    20161003, 5000, 12345, self-withdrawal, 00000000,

So I deduce the following:

    [TW Cathay credit card]
    Source Filename Pattern = unknown
    Source Filename Extension = .unknown
    Source Has Column Headers = True
    Input Columns = skip,Date,Payee,Inflow,skip,skip,skip,skip,skip,skip

    [TW Cathay debit card]
    Source Filename Pattern = unknown
    Source Filename Extension = .unknown
    Source Has Column Headers = True
    Input Columns = Date,skip,Inflow,skip,Payee,skip,skip

* Note that (just like in #152) we are faced with more than 1 header line!
* Note that `[TW Cathay credit card]` has a subtotal in the middle!?!
* Note that `[TW Cathay credit card]`  has a summary line at the bottom!
* Note that `[TW Cathay debit card]` has the date format YYYYMMDD that currently needs to be handled by a plugin.

... I think we have to abandon this one? I'm marking it as `won't fix` because it's too complex.

**Comment by nocalla** [comment]
Hmm. Interesting. I propose that we include a Start and End row feature
that can just ignore superfluous rows outside the main body of the sheet.

Does that date format definitely not work?

**Comment by torbengb** [comment]
> include a Start and End row feature

Good idea! Although for this particular format, we have zero chance of identifying the subtotal in the middle.

> date format definitely not work?

Don't actually know; I'm sitting in a hotel with a company laptop :-p

As I'm parsing all these formats, I had the idea to be able to specify the date format in the `Input Columns` line:  
rather than it just saying `...,Date,...` it could say `...,Date(YYYYMMDD),...`  
That would be an elegant way to specify it, and we could have one central place in the code where that gets translated into DD/MM/YYYY for YNAB.

I'll make separate issues for these two ideas.

**Comment by nocalla** [comment]
Uncertain exactly how to parse all of this information. 

- How many header rows and footers do we have here? We can deal with them because of #153 being implemented.
- Can we ignore the summary line?
- Can we ignore the subtotal?

**Comment by torbengb** [comment]
Looking at the translated input samples, I would say that `credit` has 3 header lines and 1 footer line, while  `withdraw` has 2 header lines and 0 footer lines. I would say we can positively ignore all of these - but we can't do anything about that subtotal in the middle.

**Comment by nocalla** [comment]
What's it subtotalling? Is it in the middle of the file, i.e. the end of a page in the statement? Or is the middle of each line.

**Comment by torbengb** [comment]
Looks like a monthly subtotal - at least going by the transaction dates above and below that line.

**Comment by nocalla** [comment]
Is it a running total every second line maybe?

**Comment by nocalla** [comment]
Or no, I can see not...it just repeats the Amount column.

**Comment by nocalla** [comment]
Hm. Yeah, not sure what we can do about this unless we get more robust
sample data.

**Comment by torbengb** [comment]
Well, if we're going to write a plugin for that format, we could just go ahead and remove any line that contains "繳款金額小計" ("subtotal"). That will match the middle line and also the last line, so if that happens then better make sure we're having `Footer Rows = 0` so we're not accidentally removing the bottom transaction as well.

**Comment by nocalla** [comment]
A potential solution the subtotal line - can we add date checking to our concept of a "valid row"? I.e. if the date row is empty, the row is invalid.

**Comment by torbengb** [comment]
> if the date [column] is empty, the row is invalid.

That makes sense. I can imagine how this wouldn't always work but it would work for this format at least.

**Comment by nocalla** [comment]
As it stands, I think we don't have enough information to make a config for this bank. Closing until we do.
