### ISSUE TITLE
Support for Personal Capital [Banking Software]

### ISSUE THREAD

**Issue by nocalla** [torbengb/bank2ynab#144]
Name of Bank: Personal Capital [Banking Software]

Source: [mgrecar/pc_to_ynab](https://github.com/mgrecar/pc_to_ynab) [Ruby]

**To be filled in as required. Delete fields that match default values.**
Source Filename Pattern = example_transaction_export_filename
Source Filename Extension = .csv
Use Regex for Filename = False
Source CSV Delimiter = ,
Source Has Column Headers = True
Input Columns = Date,Payee,Outflow,Inflow,Running Balance
Plugin =

Master issue #21

**Comment by torbengb** [comment]
I have emailed the developer (Gmail) about the default source filename pattern. Let's see if he responds; his project is unchanged since 3+ years but people tend to react on email.

**Comment by nocalla** [comment]
Thanks for the response!

@torbengb - This just requires a regex naming pattern to identify, which isn't too tricky.

**Comment by torbengb** [comment]
Thank you @mgrecar! With your information I could build this configuration:

    [Personal Capital]
    Use Regex For Filename = True
    Source Filename Pattern = [A-Z][a-z]{2} [0-9]{2}-[0-9]{4} thru [A-Z][a-z]{2} [0-9]{2}-[0-9]{4} transactions
    Source CSV Delimiter = ,
    Source Has Column Headers = True
    Input Columns = skip,Date,Payee,Inflow,Outflow,skip,Memo

Could I trouble you to verify this and edit as needed? Especially the `Input columns` would be valuable, or just copy a header (and an anonymized data row if you don't mind).

**Comment by mgrecar** [comment]
I was able to validate that the `Source Filename Pattern` you have there works fine on a sample of old source files I have, so that's great.  But, I found that the `Input Columns` were off a bit.  Here's the closest I can get:
```
Input Columns = Date,Payee,Memo,skip,skip,Amount
```
The problem is that Personal Capital doesn't break out `Inflow` and `Outflow` as separate columns, they simply provide an `Amount` column, which is positive for `Inflow` and negative for `Outflow`.  You can see how I handled that originally [here](https://github.com/mgrecar/pc_to_ynab/blob/master/convert.rb#L54).  

YNAB 4 supported importing a file with these columns:
```
Date,Payee,Category,Memo,Outflow,Inflow,Amount
```
With that format, I just set `Outflow` and `Inflow` to empty, and put the appropriate value in `Amount`.  I recall that, at the time, I found that in some YNAB custom import documentation, but I can't seem to locate that today.  

Checking the project code, it doesn't seem to support `Amount` as a concept, so there doesn't seem to be a way to map the input file to a valid YNAB import format without a code change.

To help, I'm attaching an anonymized sample file.

[Dec 16-2015 thru Jan 14-2016 transactions.csv.zip](https://github.com/torbengb/bank2ynab/files/1658474/Dec.16-2015.thru.Jan.14-2016.transactions.csv.zip)

**Comment by torbengb** [comment]
Hello Matthew, thank you so much for this feedback! YNAB understands that a
negative inflow is actually an outflow, so we can simply map the column as
Inflow. I will adjust the configuration accordingly and test with your
sample file.
Thanks again!
-Ben

**Comment by torbengb** [comment]
I've now added this to the `develop` branch. I'm curious to test how well it works, but only because it uses the ISO date format YYYY-MM-DD which YNAB doesn't automatically recognize.

**Comment by torbengb** [comment]
I've tested this config using the sample data that mgrecar provided: the file was detected and converted, and successfully imported into YNAB -- including the correct dates! :+1:
