### ISSUE TITLE
Enable projects

### ISSUE THREAD

**Issue by nocalla** [torbengb/bank2ynab#147]
Now that we've got the basic functions working, we have all lost motivation a bit! I think that enabling project boards will allow us to track goals for a 1.0 version. 

Thoughts?

**Comment by torbengb** [comment]
You're absolutely right on both counts! I've been focusing on matters in _RealLife™_ for a while, hence my lack of participation. It looks like it will go on like that for some time still. But since you mentioned it, I have now enabled the project boards -- let's see what we(you) can do with it! :-)
