### ISSUE TITLE
Improve user guide

### ISSUE THREAD

**Issue by torbengb** [torbengb/bank2ynab#15]
I want to improve/finish the [user guide in the README.md](https://github.com/torbengb/bank2ynab/blob/master/README.md#userguide) file.

**Comment by torbengb** [comment]
@nocalla can you please check step 4 of [this draft](https://github.com/torbengb/bank2ynab/blob/cosmetics/README.md#userguide) of the user guide -- is it correct for how to execute the script on Windows? Does the shortcut work if you create it as described?

**Comment by nocalla** [comment]
The execution is correct, but not the shortcut part. Have to create a batch
file. Which I've done as it happens but was excluding it from the repo. Can
include it if you like - it's just a one-liner.

**Comment by torbengb** [comment]
Yes, please add it. But what about the path in that batch file?

**Comment by nocalla** [comment]
It's local execution as if you've moved to the directory in CMD. A shortcut
to the batch file is needed to have it somewhere like the desktop though.

On 20 Oct 2017 10:58, "Torben Gundtofte-Bruun" <notifications@github.com>
wrote:

Yes, please add it. But what about the path in that batch file?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/torbengb/bank2ynab/issues/15#issuecomment-338162666>,
or mute the thread

**Comment by torbengb** [comment]
Ah, so the batch file doesn't have any `cd` command in it, makes sense. 
The user guide can say to right-click the *batch file* instead, the the "send shortcut to desktop". *Voilà!*

**Comment by nocalla** [comment]
Copy and "paste as shortcut" is how I do it anyway.

**Comment by torbengb** [comment]
I'd say this is done now. Created a pull request.
