### ISSUE TITLE
Import from ING DiBa doesn't work correctly

### ISSUE THREAD

**Issue by jd1** [torbengb/bank2ynab#196]
# Issue Report:
Script language: Python 3.6.5
Operating system: Windows
OS Version: 10

## What did you DO? (steps to reproduce)
I downloaded an export from https://banking.ing-diba.de and run _bank2ynab.bat_

The original CSV file contained the following columns:
`Buchung;Valuta;Auftraggeber/Empfänger;Buchungstext;Verwendungszweck;Betrag;Währung;Saldo;Währung`
The definition in the config file is the following:
`Input Columns = skip,skip,Payee,Memo,skip,Inflow,skip,skip,skip`

## What did you EXPECT to happen?
I would expect a CSV file that can be imported to YNAB with the correct values as defined in _Input Columns_.
This means 
- _Auftraggeber/Empfänger_ is mapped to _Payee_, 
- _Verwendungszweck_ is mapped to _Memo_ and
- _Betrag_ is mapped to _Inflow_ (or _Outflow_, I'm not sure how YNAB handles negativ inflow).

## What ACTUALLY happened?
The fixed csv files contains the columns Date, Payee, Category, Memo, Outflow and Inflow, but the values are wrong:

- _Payee_ contains the value of the field _Buchungstext_
- _Memo_ contains the value of the field _Auftraggeber/Empfänger_
- _Inflow_ contains the value of the field _Saldo_

## Can you provide other helpful information?
I know that the _Input Columns_ defines a mapping from _Buchungstext_ to _Memo_. I already tried to change this to `Input Columns = skip,skip,Payee,skip,Memo,Inflow,skip,skip,skip`, so that _Verwendungszweck_ is mapped to _Memo_, but this doesn't hel: It seems that the columns are addressed wrong.

I added a stripped down CSV export from ING DiBa and removed all sensitiv data. The zip also contains the output of the script.
[DiBa.zip](https://github.com/torbengb/bank2ynab/files/1896529/DiBa.zip)

**Comment by nocalla** [comment]
Hi JD, thanks for submitting the issue. As a non-German, I'm not sure what
the headings are supposed to mean. Can you translate all the headings in
the file please? Just so I know which one should go where!

Though our German speaker wrote this config originally I think!

**Comment by nocalla** [comment]
Also, can you try running from the terminal/command line and paste the
output - it might be that the wrong bank format is being applied to your
file.

**Comment by nocalla** [comment]
Just at a quick glance it's obvious something is wrong with the format in the config. There's no date and the first column is clearly supposed to be a date in your sample data. 

Input Columns = skip,skip,Payee,Memo,skip,Inflow,skip,skip,skip

**Comment by nocalla** [comment]
Okay, so I tried out the supplied test data and my output looks like this:

```
Date,Payee,Category,Memo,Outflow,Inflow
,VISA AMAZON EU AMAZON.DE                              ,,Gutschrift,,"5,01"
,NETFLIX INTERNATIONAL B.V.,,Lastschrifteinzug,,"-10,99"
,REWE Markt GmbH,,Lastschrifteinzug,,"-22,6"
,VISA VODAFONE GMBH VIELEN D                           ,,Lastschrifteinzug,,-15
,BARMER,,Gutschrift,,858
,"PayPal (Europe) S.a.r.l. et Cie., S.C.A.",,Lastschrifteinzug,,"-204,89"
```

Existing config from #152:
```
[DE ING-DiBa]
# source: Issue #152 (via #148)
Use Regex For Filename = True
# Umsatzanzeige_1234567890_12345678.csv
Source Filename Pattern = Umsatzanzeige_[0-9]{10}_[0-9]{8}
Source CSV Delimiter = ;
Header Rows = 7
Input Columns = skip,skip,Payee,Memo,skip,Inflow,skip,skip,skip
```

- Filename: read correct file from regex pattern and identified correct format
- CSV Delimiter: parsed correctly
- Header rows: skipped 7 rows as required
- Date column: blank - that's obviously a problem with the config. Probably a typo from original entry! Solution: the first "skip" in the config should read "Date".
- Payee column: contains the values from the "Auftraggeber/Empfänger" column, as expected.
- Category column: blank as expected
- Memo column: contains values from the "Buchungstext" column, i.e. the column before the expected "Verwendungszweck" column. Solution: add a "skip" before the "Memo" field in the config
- Outflow column: blank as expected, as we're using negative inflow to denote outflow in this particular instance
- Inflow column: contains values from Betrag column, as expected.

Proposed new config:
```
[DE ING-DiBa]
Use Regex For Filename = True
# Umsatzanzeige_1234567890_12345678.csv
Source Filename Pattern = Umsatzanzeige_[0-9]{10}_[0-9]{8}
Source CSV Delimiter = ;
Header Rows = 7
Input Columns = Date,skip,Payee,skip,Memo,Inflow,skip,skip,skip
```

This new config works for me. @jd1 - can you open bank2ynab.conf and edit the DE ING-DiBa config to match the above new config? Otherwise redownload, as I'm pushing this immediately. Please let me know if this works for you.

**Comment by jd1** [comment]
@nocalla it works, thanks!
