### ISSUE TITLE
bad handling of values

### ISSUE THREAD

**Issue by toyg** [torbengb/bank2ynab#207]
The way amounts are treated is dangerously incorrect. I'm referring to line 470 and potentially others I've not checked.

1. `float()` is not precise and can result in rounding errors. Financial data should always use `decimal.Decimal()`.
2. there is currently no handling of cases where decimal/thousand separators in records differ from what the system uses. E.g. on a US system I wouldn't be able to import files with European formats. Admittedly this is a relatively rare case, but most financial systems let you override separators in case you need to do so.

1 is definitely an issue that needs to be fixed. 2 is more of a feature request. 

Both problems would go away if the handling were to be reverted to pure text, as it was before the "fix inflow depending on column" addition. Basically you would have to check for + or - in the first character, then change it to what you want. This would kill two birds with one stone.

**Comment by nocalla** [comment]
Thanks for pointing this out. It's a straightforward fix to return to
string handling. Just requires inserting a minus sign rather than checking
for one.

Regarding the 2nd point, YNAB has its own setting about separators, so I'd
assume that individual users would have it set to their locale's
preference. That said, we have working banks that use commas as decimal
places.
