### ISSUE TITLE
Use Payees for Memo configuration is ignored

### ISSUE THREAD

**Issue by gczobel** [torbengb/bank2ynab#216]
*Dear submitter, please edit the following according to your needs. Thank you!*

**Describe the bug**
The option "Use Payees for Memo" is ignored. This configuration is used on the bank [IE AIB Ireland].

**What did you EXPECT to happen?**
Use Payees for Memo = False is expected to not copy the Payee into the Memo field and leave it blank.

**What ACTUALLY happened?**
Payee is always copied to Memo field.

**What did you DO? (steps to reproduce)**
1 Changed configuration. Value is ignored.

**What's your software environment?**
 - Script language: Python 3.5
 - Operating system: Windows
 - OS version: 10

**Can you provide other helpful information?**

**Attachments**
If applicable, add sample files or screenshots to help explain your problem.

**Comment by gczobel** [comment]
The truth is that I removed the code that copies the Payee into the Memo.
I don't understand why payee name in the Memo can be useful.

In my case, my card has a field just in case an item is paid in installments and I put this info in the Memo field, so every month I see something like "Installment x of y". Mixing this with Payee name is ugly.

If you can put again the code will be great!

**Comment by nocalla** [comment]
What I'd suggest then is that you make that installment column the "memo" field in your version of the configuration. There's a custom configuration file that you can modify that overwrites the one in the main configuration file. If you do the following in user_configuration.conf, for example, it'll overwrite the parameters from the main file, using the 2nd-last column as a Memo field instead of skipping it.
```
[IE AIB Ireland]
Input Columns = skip,Date,Payee,Inflow,Outflow,Memo,skip
```
In fact, maybe we need to update our AIB config to use the field you've mentioned.

**Comment by nocalla** [comment]
Added the functionality to the code for using "Use Payees for Memo" in configuration files.
