### ISSUE TITLE
Python 2.x Support

### ISSUE THREAD

**Issue by nocalla** [torbengb/bank2ynab#25]
As requested by [u/fio_smiles](https://www.reddit.com/r/ynab/comments/77d7rt/tools_bank2ynab_heres_a_script_that_helps_with/dol9p0u/), this may be possible. Need handling for the following main issues:

- [x] ConfigParser to configparser
- [x] csv delimiter as string, not unicode
- [x] csv newline invalid

Assigning myself to this issue. It's not a high importance item, but might help prevent problems if @torbengb starts accidentally using Python 2 again...

**Comment by torbengb** [comment]
As a relevant side-note and reference, [here's why Python 2 is still default on Linux](https://askubuntu.com/a/590030/5786) even though 3.x is factory-installed as well. 
TLDR: A ton of system programs use Python and haven't been ported to Python 3 yet. Any attempt to force the system default to Python 3 would cause big trouble outside of `bank2ynab`.

**Comment by toyg** [comment]
I've pushed a separate py2 branch at 98c0a17cc583d52f9a78af9c8f0befa6bd76ff3e as a playground for this work. I took care of differences in stdlib name and interfaces, and now it seems to run fine with both 2 and 3. Tested with Python 2.7.10 and 3.6.1 on OSX, would be good if somebody could test on Windows before it's merged, because one of the renamed modules is `winreg`; and ideally with python < 3.6 (although I don't expect any breakage on 3.4+).

Not sure what you mean by "csv delimiter as string, not unicode", because `csv` seems to take care of business without any particular handling...?

**Comment by nocalla** [comment]
It's referenced in more detail over on the py2 branch at #26. Will test out on Windows and merge into the py2 testing branch.

**Comment by torbengb** [comment]
I can also test on Linux tonight = v2.7 and 3.5.1

**Comment by nocalla** [comment]
Issues listed probably fixed in latest master push. Closing to clean up issues. We can reopen if need be.
