### ISSUE TITLE
Use payee for memo if no existing memo

### ISSUE THREAD

**Issue by nocalla** [torbengb/bank2ynab#28]
I'll change how my payee swap thing works to just use payee info only if memo is blank or there's no memo column. I think this is logical behaviour for a default setting and doesn't really need a switch on the configuration. Thoughts?

**Comment by torbengb** [comment]
Personally I prefer to not have Payee autofilled because the bank statements have long weird strings there instead of just the store names. So I am happy with having the Payee in the Memo always. But also, on my VISA statement the Memo field is actually used and helpful (it often shows the city and country of expense, which is very useful to me).

Would it make sense to you to change the parameter from a binary switch to a separate parameter per target column?

Fill payee column with = Payee | nothing
Fill memo column with = Memo | Payee | Payee+Memo | nothing

See, don't ask me such questions :-) I just blow things out of proportion!

**Comment by nocalla** [comment]
The payee is kinda standard info on all statements though really, it's the memo that's often not populated. If you want both blank it's just a matter of giving different input columns to the config, i.e instead of date,payee,memo,inflow say date,skip,skip,inflow. It'll look for payee and just leave it blank.

**Comment by nocalla** [comment]
My suggestion wasn't to always override memo with payee but to fill empty memo fields with the payee.
