### ISSUE TITLE
[Feature] skip records in file

### ISSUE THREAD

**Issue by fiosmiles** [torbengb/bank2ynab#38]
Script language: Python2.7
Operating system: Windows
OS Version: 10

Request:
I'd like to be able to specify a switch in the config to remove non-transaction data from being written into my import file.

Background:
One thing that my bank puts into the records is when interest rates change, etc, and this gives records which I end up deleting prior to or after import, if I withdraw from an ATM either I get a second row of identifying information which is irrelevant for YNAB.

Approach idea:
- add a switch into the config 
- add a test condition into the writer (I've done this locally in a version I can play with and try to push if of interest) which checks for input and output blanks in the row
- bypass the writing of the row if it's a non-transaction

Thoughts?

**Comment by nocalla** [comment]
That's a weird thing to put mid statement. Is there a defining way it's
phrased in the row? If there is, that'd be easy enough to check for in the
row fixing function. I'd like to see your test case. If you don't want to
push it you can paste a code snippet here.

On 21 Oct 2017 23:39, "fiosmiles" <notifications@github.com> wrote:

Script language: Python2.7
Operating system: Windows
OS Version: 10

Request:
I'd like to be able to specify a switch in the config to remove
non-transaction data from being written into my import file.

Background:
One thing that my bank puts into the records is when interest rates change,
etc, and this gives records which I end up deleting prior to or after
import, if I withdraw from an ATM either I get a second row of identifying
information which is irrelevant for YNAB.

Approach idea:

   - add a switch into the config
   - add a test condition into the writer (I've done this locally in a
   version I can play with and try to push if of interest) which checks for
   input and output blanks in the row
   - bypass the writing of the row if it's a non-transaction

Thoughts?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/torbengb/bank2ynab/issues/38>, or mute the thread

**Comment by torbengb** [comment]
Add it as test data please. 
I see such lines on my online statement too, but thankfully it's not included in the CSV download.

**Comment by nocalla** [comment]
I think this commit may help. Please test it out @fiosmiles.

**Comment by nocalla** [comment]
This issue should be resolved by the commit mentioned. Closing. Please let me know if it hasn't solved your issue!
