### ISSUE TITLE
create documentation about working with plugins

### ISSUE THREAD

**Issue by torbengb** [torbengb/bank2ynab#82]
As noted in issue #81 we need documentation about the plugin concept. 

For starters that will probably be wiki. Perhaps migrate content to the GitHub "SRT" format later?

**Comment by toyg** [comment]
Yes please. Check out the comments in plugins/null.py and let me know if they are not clear. Am happy to help once that stuff is migrated wherever you think is best.

**Comment by toyg** [comment]
And to reiterate what I stated elsewhere: this is an extension mechanism that is completely optional and only really useful when the import format cannot be dealt with the standard config directives. Having to know Python is obviously a pretty high barrier for most users. Most documentation will be for developers.

Basically the thought process of a regular user should be:
1. add config parameters in the usual way; if it works, done.
2. if it fails because the format is too complex, look if there is an available plugin for your bank, enable it in configuration (by adding "Plugins = mybank"), try again. If it fails again, open an issue.
3. if there isn't a plugin available, either create it yourself (if you know python) or open an issue providing a sample file to parse, and we'll create one.

The mechanism can also be used to do things like downloading files from a website.

**Comment by torbengb** [comment]
I've written a page about this now: https://github.com/torbengb/bank2ynab/wiki/WorkingWithPlugins

It references a page about date formats, but that doesn't yet exist and I don't think we need it?

**Comment by nocalla** [comment]
Looks okay to me. We'll likely have to update the docs as we work out what sort of things need to be done or what can be actually done with the base code, but it's fine for now.

Close #82.
