### ISSUE TITLE
Date parsing

### ISSUE THREAD

**Issue by toyg** [torbengb/bank2ynab#84]
Looking at the various converter scripts, one of the recurring conversions that have to be done is date parsing. Some banks use '-' as separator, some (for example [Rabobank](https://github.com/jtdev/ynab-converter/blob/master/src/RabobankYnabConverter.java) ) have no separator at all...

Python already has [syntax for date parsing](https://docs.python.org/2/library/datetime.html#strftime-strptime-behavior), so we should probably just have an optional parameter to surface it when necessary.

Date formats accepted by YNAB are [documented here](https://classic.youneedabudget.com/support/article/csv-file-importing).

**Comment by nocalla** [comment]
The relevant quote from the YNAB site for quick reference. 

> Any field can be left blank except the date. Valid date formats:
> 
> DD/MM/YY
> DD/MM/YYYY
> DD/MM//YYYY
> MM/DD/YY
> MM/DD/YYYY
> MM/DD//YYYY

**Comment by nocalla** [comment]
I wonder is there undocumented support for other formats, as @torbengb has dates using `.` as a separator...

I think needing to parse an arbitrary date is an unreasonable expectation for the script, as outlier cases would confuse things. Would it make sense to just include a default date format and allow that to be changed in each config?

**Comment by toyg** [comment]
I think the default behaviour should be to leave the string untouched, because clearly YNAB actually support more formats than they are letting on. 
However, it could be good to have the feature (again, disabled by default) to do more complex parsing if it can avoid having to write a full plugin for each bank that has a simple csv except for the date.

Maybe we can review this once we have a sizeable number of examples that are forced into plugins because of date format.

**Comment by nocalla** [comment]
Could just include a date parsing string formatting field if a bank requires it. I don't think it merits a plugin, as it's a reasonably straightforward task to accomplish.

**Comment by nocalla** [comment]
Just for reference, the Rabobank format does *not* get imported successfully into YNAB. 
20170102, i.e. YYYYMMDD with no separators.

**Comment by torbengb** [comment]
It would appear that YNAB accepts _any_ separator but there must _be_ a separator, eh? So yeah, we still need a way to handle dates. Dang.

**Comment by nocalla** [comment]
I think what makes sense from the discussion above is that we do the following:

- Add a "Date Format" config field
- Have it be **blank** by default so that YNAB can handle the undocumented formats

I'll work on this in the [84_date_parsing](https://github.com/torbengb/bank2ynab/tree/feature/84_date_parsing) branch.

**Comment by nocalla** [comment]
That was surprisingly easy to do with the strftime and strptime functions! We just have to provide the date format string in a format that is compatible, as outlined in the link provided at the start of this issue, e.g. for Rabo: %%Y%%m%%d - the % sign has to be doubled up in our config file so that the config parser interprets it as a string rather than as a placeholder for something.

**Comment by torbengb** [comment]
And you got rid of the Rabobank plugin! I like it! :+1:
